#!/bin/bash

# ./build <target> <debug/release> <optimisation>

###############
### Settings. #
###############
buildDirectory="out"

compiler="gcc"

preprocessFlags="-E"
# (E) Only run preprocessor.

assembleFlags="-S"

compileFlags="-pthread -lrt -c -Werror -Wall -Wextra -pedantic -Wno-unused-parameter -std=c11 -march=native"
# (pthread) Use POSIX threading.
# (lrt) POSIX.1b realtime extension library.
# (c) Compile without linking.
# (Werror) Turn all warnings in to errors.
# (Wall) Turn on "all" warnings.
# (Wextra) Turn on extra warnings not included in 'Wall'.
# (pedantic-errors) Issue all the warnings demanded by strict ISO C and turns them into errors.
# (Wno-unused-parameter) Don't warn about unused parameter.
# (std=c11) Use C11 (C standard revision) ISO/IEC 9899:2011.
# (march=native) Use CPU/Architecture dependent optimisations. See:'https://stackoverflow.com/questions/14492436/g-optimization-beyond-o3-ofast' for more optimisation flags.

additionalDebugFlags="-D DEBUG"

additionalReleaseFlags="-D NDEBUG"

linkFlags="-pthread -lrt"

libraries="-lpthread"

# Halt on the first error.
set -e

######################
### Build functions. #
######################

# prepareBuildDirectory(buildDirectory)
prepareBuildDirectory(){
    # Remove build directory if already present.
    if [ -d "$1" ]; then
        rm -r $1
    fi

    # Create build directory.
    mkdir $1
}

# preprocess(compiler, "compilerFlags", buildDirectory, fileName)
preprocess(){
    # Add 'src' directory to directory stack.
    pushd src > /dev/null

    # If 'time' command is available.
    if hash time 2>/dev/null; then
        printf "Preprocessing:\n"

        \time --format '\tUser time: %Us\n\tSystem time: %Ss\n\tCPU utilization: %P' $1 $2 -o ../$3/$4.i $4.c
    else
        printf "Preprocessing...\n"

        $1 $2 -o ../$3/$4.i $4.c

        printf "Install the 'time' package to get timing information about the compilation process."
    fi

    popd > /dev/null
}

# assemble(compiler, "compilerFlags", buildDirectory, fileName)
assemble(){
    # Add 'src' directory to directory stack.
    pushd src > /dev/null

    # If 'time' command is available.
    if hash time 2>/dev/null; then
        printf "Assembling:\n"

        \time --format '\tUser time: %Us\n\tSystem time: %Ss\n\tCPU utilization: %P' $1 $2 -o ../$3/$4.s ../$3/$4.i
    else
        printf "Assembling...\n"

        $1 $2 -o ../$3/$4.s ../$3/$4.i

        printf "Install the 'time' package to get timing information about the compilation process."
    fi

    popd > /dev/null
}

# compile(compiler, "compilerFlags", buildDirectory, inputFileName, outputFileName)
compile(){
    # Add 'src' directory to directory stack.
    pushd src >/dev/null

    # If 'time' command is available.
    if hash time 2>/dev/null; then
        printf "Compiling:\n"

         \time --format '\tUser time: %Us\n\tSystem time: %Ss\n\tCPU utilization: %P' $1 $2 -o ../$3/$5 $4
    else
        printf "Compiling...\n"

        $1 $2 -o ../$3/$5 $4

        printf "Install the 'time' package to get timing information about the compilation process."
    fi

    popd > /dev/null
}

# link(compiler, "linkFlags", "libraries", buildDirectory, objectFileName, executableName)
link(){
    # Add build directory directory to directory stack.
    pushd $4 > /dev/null
    
    # If 'time' command is available.
    if hash time 2>/dev/null; then
        printf "Linking:\n"

        \time --format '\tUser time: %Us\n\tSystem time: %Ss\n\tCPU utilization: %P' $1 $2 $3 -o ../$6 ../$4/$5.o
    else
        printf "Linking...\n"

        $1 $2 $3 -o ../$6 ../$4/$5.o

        printf "Install the 'time' package to get timing information about the compilation process."
    fi

    popd >/dev/null
}

# buildRelease(fileName, executableName)
buildRelease(){
    prepareBuildDirectory $buildDirectory

    preprocess $compiler "$preprocessFlags" $buildDirectory $1

    assemble $compiler "$assembleFlags" $buildDirectory $1

    compile $compiler "$compileFlags" $buildDirectory "../$buildDirectory/$1.s" "$1.o"

    link $compiler "$linkFlags" "$libraries" $buildDirectory $1 $2

    # Remove build directory.
    rm -r $buildDirectory
}

# buildDebug(fileName, executableName)
buildDebug(){
    prepareBuildDirectory $buildDirectory

    compile $compiler "$compileFlags" $buildDirectory "$1.c" "$1.o"

    link $compiler "$linkFlags" "$libraries" $buildDirectory $1 $2

    # Remove build directory.
    rm -r $buildDirectory
}

# buildAndRunTest(fileName, executableName)
buildAndRunTest(){
    # Create temporary test directory.
    if [ -d "./tmp/" ]; then
        rm -r "./tmp/"
    fi

    mkdir "./tmp/"

    # Remove old executable.
    if [ -d "$2" ]; then
        rm $2
    fi

    compileFlags="$compileFlags -D TEST_BUILD"

    buildDebug $1 $2

    # Don't halt on errors.
    set +e

    # If valgrind is available.
    if hash valgrind 2>/dev/null; then
            valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all ./$2
    else
        # Run test executable.
        ./$2
    fi

    # Remove temporary test directory.
    rm -r "./tmp/"
}

# printBuildOptions(void)
printBuildOptions(){
    printf "Usage 'build <target> <debug/release> <optimisation>'.\n "
    printf "\tTargets:[herder, server, all, test], Optimisation:[0-3].\n"
}

#########################
### Begin build script. #
#########################
clear
clear

# Print build options if no arguments were paresed.
if [ $# -eq 0 ]; then
    printBuildOptions

    exit -1
fi

if [ $# -eq 1 ]; then
    # Build and Run the test executable.
    if [ "$1" == "test" ]; then
        compileFlags="$compileFlags -O0 -g $additionalDebugFlags"

        buildAndRunTest test herder_test

        exit 0
    fi
fi

if [ $# -eq 2 ]; then
    if [ "$2" == "debug" ]; then
        compileFlags="$compileFlags -O0 -g $additionalDebugFlags"

        if [ "$1" == "herder" ]; then
            buildDebug consoleClient herder

            exit 0
        else
            if [ "$1" == "server" ]; then
                buildDebug server herderServerDaemon

                exit 0
            else
                if [ "$1" == "all" ]; then
                    buildDebug consoleClient herder

                    printf "\n"

                    buildDebug server herderServerDaemon
                    
                    exit 0
                fi
            fi
        fi
    fi
fi

if [ $# -eq 3 ]; then
    if [ "$2" == "release" ]; then
        if [ "$1" == "herder" ] || [ "$1" == "server" ] || [ "$1" == "all" ]; then
            if [ "$3" == "0" ] || [ "$3" == "1" ] || [ "$3" == "2" ] || [ "$3" == "3" ]; then
                if [ "$3" == "0" ]; then
                    compileFlags="$compileFlags -O0 $additionalReleaseFlags"
                else
                    if [ "$3" == "1" ]; then
                        compileFlags="$compileFlags -O1 $additionalReleaseFlags"
                    else
                        if [ "$3" == "2" ]; then
                            compileFlags="$compileFlags -O2 $additionalReleaseFlags"
                        else
                            if [ "$3" == "3" ]; then
                                compileFlags="$compileFlags -O3 $additionalReleaseFlags"
                            fi
                        fi
                    fi
                fi

                if [ "$1" == "herder" ]; then
                    buildRelease consoleClient herder

                    printf "\nBuild completeted.\n"

                    exit 0
                fi

                if [ "$1" == "server" ]; then
                    buildDebug server herderServerDaemon

                    printf "\nBuild completeted.\n"

                    exit 0
                fi

                if [ "$1" == "all" ]; then
                    buildRelease consoleClient herder

                    printf "\n"

                    buildDebug server herderServerDaemon

                    printf "\nBuild completeted.\n"

                    exit 0
                fi
            fi
        fi
    fi
fi

printBuildOptions

exit -1